### ISSUE TITLE
slicer files locking up printers

### ISSUE THREAD

**Issue by cjbeckjr** [ankermake/AnkerMake-PrusaSlicer-Release#3]
After testing the prusa slicer it fails to produce functioning files for AnkerMake printers, it locks the M5 printers up with no recovery except for power down and restart and during the lockup the hotend continues to heat and extruder continues to run.

After testing this slicer once and reverting to the original slicer the printer required a full firmware reversal just to get printer to accept files.
Also noted that most "features" do not appear to have a function
When utilizing autolevel this function is overridden with the slicer causing an unneeded offset of the nozzle to the print surface. Usually causes "blob" print.
I have also noted that when accessing account information the handler now forces logout of all computers working with the printer and requires a re-login while working in the application. This has now transferred into the original slicer also.
I have sent the log files to support for the noted issues

**Comment by AnkerAllen** [comment]
@cjbeckjr Thank you for your feedback, please try with the latest version, if you still encounter problems, please contact us.
