### ISSUE TITLE
Log In Issues on AnkerMake Studio (The email or password you entered is incorrect.)

### ISSUE THREAD

**Issue by iamhmh** [ankermake/AnkerMake-PrusaSlicer-Release#39]
Hi, I have a problem when I want to log in to the AnkerMake Studio software, here is :
-I click on Account > Log In (Nothing special so far);
-I enter my log in credentials and click on "Sign In";
-I select the country and press "Confirm";

And then, I got "The email or password you entered is incorrect.", but it's the correct credentials.

I click on "Forgot password?", I change my password, and I got the same message "The email or password you entered is incorrect.".

I try to create another account, I verify my other email, and then I got the same message "The email or password you entered is incorrect.".

I try to change the version of AnkerMake Studio, I took the 1.5.24, the 1.5.23, the 1.5.22 and the 1.5.19, I got the same issues in every version I've try.

Did anyone else have the same issue? Did someone fix it?

Thank you for your help !

**Comment by Anker-louisdu** [comment]
Could you please provide your login account? @iamhmh @SantyagoSeaman

**Comment by SantyagoSeaman** [comment]
@Anker-louisdu makeev.alex@gmail.com

**Comment by spl1974** [comment]
Same here: spl1974@gmail.com

**Comment by rosetown-kelly** [comment]
I am experiencing the same issue. I have tried resetting the password multiple times. I can log into the website portal not problem, but can not login to AnkerMake studio.

**Comment by nfranke1** [comment]
Today Morning (Germany) it worked. Last Night no log in Possible for me as well.

**Comment by spl1974** [comment]
Same here (Germany too). Login works again.

**Comment by Anker-louisdu** [comment]
We have fixed the above issue, sorry for the inconvenience caused to you, thanks again for your attention and trust in our products, hope you have a good experience. @SantyagoSeaman @iamhmh @nfranke1 @rosetown-kelly @spl1974

**Comment by iamhmh** [comment]
Same here (France), Login works again, Thanks for the support @Anker-louisdu !

**Comment by SantyagoSeaman** [comment]
@iamhmh Thank you so much!
