### ISSUE TITLE
jansson.h missing from repo

### ISSUE THREAD

**Issue by mgradwohl** [ankermake/AnkerMake-PrusaSlicer-Release#4]
Compiling on Windows, getting this

Error	C1083	Cannot open include file: 'jansson.h': No such file or directory	libslic3r_gui	D:\source\AnkerMake-PrusaSlicer-Release\AnkerStudio\src\slic3r\GUI\Network\DeviceObject.h	4

**Comment by samuelwang1990** [comment]
Have you installed the jansson lib?

**Comment by mgradwohl** [comment]
where in the instructions does it say to do that? 🙂

**Comment by samuelwang1990** [comment]
in Readme.md you should compile the deps libs. 1. cd deps;mkdir deps_build;cd deps_build;
2. cmake  -DCMAKE_BUILD_TYPE=Debug -S .. -G "Visual Studio 16 2019";
3. Open the project and build the dependency library: {path}/AnkerStudio/deps/deps_build/destdir;
4. Set system environment variables:  THIRD_PART_ROOT = {path}/AnkerStudio/deps/deps_build/destdir;
5. mkdir AnkerStudio/build && AnkerStudio/build;
6. cmake -DCMAKE_BUILD_TYPE=Debug -S .. -G "Visual Studio 16 2019";
7. Open the project and build;

**Comment by mgradwohl** [comment]
I did build the deps.  I'm pretty sure you left it out.

![image](https://github.com/ankermake/AnkerMake-PrusaSlicer-Release/assets/3945134/58c8b7be-8f1e-4d21-8a3f-8b7bacbcbe53)

**Comment by samuelwang1990** [comment]
Relevant instructions have been added, thank you for pointing it out.

**Comment by joscha** [comment]
Closed via a26dc81cf9dfdd1e42037c92dea14f2307072d17
