### ISSUE TITLE
Readme should instruct users to install CMake

### ISSUE THREAD

**Issue by mgradwohl** [ankermake/AnkerMake-PrusaSlicer-Release#5]
Building clearly requires CMake but the readme does not call that out. Simple add.

**Comment by joscha** [comment]
References #5, #4, #2.

Can we possibly add a nix profile to the source with all necessary requirements?

**Comment by AnkerAllen** [comment]
@mgradwohl Thank you for your feedback, we'll add a note on this in the next open source release.
