### ISSUE TITLE
AnkerMake Studio defaults to M5 printer even if you have an M5C configured

### ISSUE THREAD

**Issue by mgradwohl** [ankermake/AnkerMake-PrusaSlicer-Release#7]
On launch AnkerMake Studio should default to the printer you have, or the custom profile you've created, not the M5.

**Comment by joscha** [comment]
References #1

**Comment by AnkerKristy** [comment]
We apologize for this inconvenience have caused. This issue has been fixed in version V1.5.17, and we hope you can update to this version to try it out. If you have any further questions, please feel free to let us know. @mgradwohl @joscha
